# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb0518284b62f9e8670a5b12f2e237813d6be8be93d78518f0e8d7f53d82071bfae31e1cd924adba37b1a26f54a802d2b4bbc380243aa0852c91c054ed5f7594

test:
  secret_key_base: 07d8a43e06bf03dc3ac52def5713b8fe89458e4d3d4d84f0f888ec87489b0c78c8ebb62347cb804bf1a8c454d1e4aa18df70f624eed80482c3a3295e0db9a4c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
